;;; mantle/config/dev-env/web.el --- Development Environment -*- lexical-binding: t; -*-
;;
;; Author:     Cole Brown <http://github/cole-brown>
;; Maintainer: Cole Brown <code@brown.dev>
;; Created:    2023-01-05
;; Modified:   2023-01-05
;; URL:        https://github.com/cole-brown/.config-emacs
;;
;; These are not the GNU Emacs droids you're looking for.
;; We can go about our business.
;; Move along.
;;
;;; Commentary:
;;
;;  Development Environment
;;
;;; Code:


(imp:require :keybind)


;;------------------------------------------------------------------------------
;; Keybinds: General Infixes
;;------------------------------------------------------------------------------
;; Define the infix with the title here so we don't have to worry about what's
;; defined in what order since you can only define the title once or else things
;; overwrite each other?
;;
;; TODO: Make sure that's a correct assumption. Currently only 87% sure.

(keybind:leader/local:def
 :keymaps (list 'web-mode-map keybind:leader/local:keymaps)
 :infix (keybind:infix "a")
 "" '(nil :which-key "attribute..."))


(keybind:leader/local:def
 :keymaps (list 'web-mode-map keybind:leader/local:keymaps)
 :infix (keybind:infix "b")
 "" '(nil :which-key "block..."))


(keybind:leader/local:def
 :keymaps (list 'web-mode-map keybind:leader/local:keymaps)
 :infix (keybind:infix "d")
 "" '(nil :which-key "dom..."))


(keybind:leader/local:def
 :keymaps (list 'web-mode-map keybind:leader/local:keymaps)
 :infix (keybind:infix "e")
 "" '(nil :which-key "element..."))


(keybind:leader/local:def
 :keymaps (list 'web-mode-map keybind:leader/local:keymaps)
 :infix (keybind:infix "t")
 "" '(nil :which-key "tag..."))


;;------------------------------------------------------------------------------
;; Vue
;;------------------------------------------------------------------------------
;; NOTE: If I start needing to touch front-end stuff, we use Vue so try:
;;   - https://github.com/AdamNiederer/vue-mode
;;   - https://github.com/AdamNiederer/vue-html-mode


;;------------------------------------------------------------------------------
;; Web
;;------------------------------------------------------------------------------

(imp:use-package web-mode
  :ensure nil ; This is an Emacs built-in feature.

  :mode "\\.[px]?html?\\'" ; Will make `web-mode' responsible for normal "*.html"/"*.htm" files
  :mode "\\.\\(?:tpl\\|blade\\)\\(?:\\.php\\)?\\'"
  :mode "\\.erb\\'"
  :mode "\\.[lh]?eex\\'"
  :mode "\\.sface\\'"
  :mode "\\.jsp\\'"
  :mode "\\.as[cp]x\\'"
  :mode "\\.ejs\\'"
  :mode "\\.hbs\\'"
  :mode "\\.mustache\\'"
  :mode "\\.svelte\\'"
  :mode "\\.twig\\'"
  :mode "\\.jinja2?\\'"
  :mode "\\.eco\\'"
  :mode "wp-content/themes/.+/.+\\.php\\'"
  :mode "templates/.+\\.php\\'"

  ;;------------------------------
  :init
  ;;------------------------------

  (innit:hook:defun
     (:name   'web:settings
      :file   macro<imp>:path/file
      :docstr "Settings for Web mode. Non-LSP stuff.")

   ;; Nothing currently, I guess?

   ;; Separate camel-case into separate words?
   ;; (subword-mode t)
   )


  (innit:hook:defun
     (:name   'web:fix-js-comments
      :file   macro<imp>:path/file
      :docstr "Fix comment handling in `web-mode' for JavaScript.")
   (when (member web-mode-content-type '("javascript" "jsx"))
     ;; For some reason the default is to insert HTML comments even
     ;; in JavaScript.
     (setq-local comment-start "//")
     (setq-local comment-end "")
     ;; Needed since otherwise the default value generated by
     ;; `comment-normalize-vars' will key off the syntax and think
     ;; that a single "/" starts a comment, which completely borks
     ;; auto-fill.
     (setq-local comment-start-skip "// *")))


  ;;------------------------------
  ;; NOTE: Vue Fallback Mode: `:init'
  ;;------------------------------
  ;; If the user has installed `vue-mode' then, by appending this to
  ;; `auto-mode-alist' rather than prepending it, its autoload will have
  ;; priority over this one.
  (add-to-list 'auto-mode-alist '("\\.vue\\'" . web-mode) 'append)


  ;;------------------------------
  ;; NOTE: Vue Fallback Mode: `:mode'
  ;; I think this has to happen after `add-to-list' so it doesn't get prepended by `use-package'?
  :mode "\\.vue\\'"
  ;;------------------------------


  ;;------------------------------
  :hook
  ;;------------------------------
  ((web-mode-hook . mantle:hook:web:settings)
   (web-mode-hook . mantle:hook:web:fix-js-comments))


  ;;------------------------------
  :custom
  ;;------------------------------

  ;; These default to 2 if `standard-indent' is not `boundp' and truthy.
  (web-mode-markup-indent-offset (jerky:get 'code 'tab 'standard))

  (web-mode-enable-html-entities-fontification t)

  ;; (web-mode-auto-close-style 1)


  ;;------------------------------
  :general
  ;;------------------------------
  ;;---
  ;; Attribute
  ;;---
  (:prefix  (keybind:prefix :local "a")
   :states  keybind:leader/local:states
   :keymaps (list 'web-mode-map keybind:leader/local:keymaps)
   "b" (list #'web-mode-attribute-beginning :which-key "Beginning")
   "e" (list #'web-mode-attribute-end       :which-key "End")
   "i" (list #'web-mode-attribute-insert    :which-key "Insert")
   "n" (list #'web-mode-attribute-next      :which-key "Next")
   "s" (list #'web-mode-attribute-select    :which-key "Select")
   "k" (list #'web-mode-attribute-kill      :which-key "Kill")
   "p" (list #'web-mode-attribute-previous  :which-key "Previous")
   "t" (list #'web-mode-attribute-transpose :which-key "Transpose"))

  ;;---
  ;; Block
  ;;---
  (:prefix  (keybind:prefix :local "b")
   :states  keybind:leader/local:states
   :keymaps (list 'web-mode-map keybind:leader/local:keymaps)
   "b" (list #'web-mode-block-beginning :which-key "Beginning")
   "c" (list #'web-mode-block-close     :which-key "Close")
   "e" (list #'web-mode-block-end       :which-key "End")
   "k" (list #'web-mode-block-kill      :which-key "Kill")
   "n" (list #'web-mode-block-next      :which-key "Next")
   "p" (list #'web-mode-block-previous  :which-key "Previous")
   "s" (list #'web-mode-block-select    :which-key "Select"))

  ;;---
  ;; DOM
  ;;---
  (:prefix  (keybind:prefix :local "d")
   :states  keybind:leader/local:states
   :keymaps (list 'web-mode-map keybind:leader/local:keymaps)
   "a" (list #'web-mode-dom-apostrophes-replace :which-key "Replace Apostrophies")
   "d" (list #'web-mode-dom-errors-show         :which-key "Show Errors")
   "e" (list #'web-mode-dom-entities-encode     :which-key "Encode Entities")
   "n" (list #'web-mode-dom-normalize           :which-key "Normalize")
   "q" (list #'web-mode-dom-quotes-replace      :which-key "Replace Quotes")
   "t" (list #'web-mode-dom-traverse            :which-key "Traverse")
   "x" (list #'web-mode-dom-xpath               :which-key "XPath"))

  ;;---
  ;; Element
  ;;---
  (:prefix  (keybind:prefix :local "e")
   :states  keybind:leader/local:states
   :keymaps (list 'web-mode-map keybind:leader/local:keymaps)
    "/" (list #'web-mode-element-close                   :which-key "Close")
    "a" (list #'web-mode-element-content-select          :which-key "Select Content")
    "b" (list #'web-mode-element-beginning               :which-key "Beginning")
    "c" (list #'web-mode-element-clone                   :which-key "Clone")
    "d" (list #'web-mode-element-child                   :which-key "Child")
    "e" (list #'web-mode-element-end                     :which-key "End")
    "f" (list #'web-mode-element-children-fold-or-unfold :which-key "Fold/Unfold Children")
    "i" (list #'web-mode-element-insert                  :which-key "Insert")
    "k" (list #'web-mode-element-kill                    :which-key "Kill")
    "m" (list #'web-mode-element-mute-blanks             :which-key "Mute Blanks")
    "n" (list #'web-mode-element-next                    :which-key "Next")
    "p" (list #'web-mode-element-previous                :which-key "Previous")
    "r" (list #'web-mode-element-rename                  :which-key "Rename")
    "s" (list #'web-mode-element-select                  :which-key "Select")
    "t" (list #'web-mode-element-transpose               :which-key "Transpose")
    "u" (list #'web-mode-element-parent                  :which-key "Parent")
    "v" (list #'web-mode-element-vanish                  :which-key "Vanish")
    "w" (list #'web-mode-element-wrap                    :which-key "Wrap"))

  ;;---
  ;; Tag
  ;;---
  (:prefix  (keybind:prefix :local "t")
   :states  keybind:leader/local:states
   :keymaps (list 'web-mode-map keybind:leader/local:keymaps)
   "a" (list #'web-mode-tag-attributes-sort :which-key "Sort Attributes")
   "b" (list #'web-mode-tag-beginning       :which-key "Beginning")
   "e" (list #'web-mode-tag-end             :which-key "End")
   "m" (list #'web-mode-tag-match           :which-key "Match")
   "n" (list #'web-mode-tag-next            :which-key "Next")
   "p" (list #'web-mode-tag-previous        :which-key "Previous")
   "s" (list #'web-mode-tag-select          :which-key "Select"))

  ;;---
  ;; Leader: Local
  ;;---
  (:prefix  (keybind:prefix :local)
   :states  keybind:leader/local:states
   :keymaps (list 'web-mode-map keybind:leader/local:keymaps)

   "h" (list #'web-mode-reload        :which-key "Rehighlight Buffer")
   "i" (list #'web-mode-buffer-indent :which-key "Indent Buffer"))

  ;;---
  ;; Leaderless
  ;;---
  (:states '(global)
   :keymaps (list 'web-mode-map keybind:leader/global:keymaps)
   (list "M-/" #'web-mode-comment-or-uncomment :which-key "Comment/Uncomment"))

  (:states '(insert)
   :keymaps (list 'web-mode-map keybind:leader/global:keymaps)
   "SPC" #'self-insert-command)

  (:states '(normal)
   :keymaps (list 'web-mode-map keybind:leader/global:keymaps)
   (list "za"  #'web-mode-fold-or-unfold :which-key "Fold/Unfold"))

  (:states '(normal visual)
   :keymaps (list 'web-mode-map keybind:leader/global:keymaps)
   (list "]a"  #'web-mode-attribute-next     :which-key "Attribute: Next")
   (list "[a"  #'web-mode-attribute-previous :which-key "Attribute: Previous")
   (list "]t"  #'web-mode-tag-next           :which-key "Tag: Next")
   (list "[t"  #'web-mode-tag-previous       :which-key "Tag: Previous")
   (list "]T"  #'web-mode-element-child      :which-key "Child: Next")
   (list "[T"  #'web-mode-element-parent     :which-key "Child: Previous"))


  ;;------------------------------
  :config
  ;;------------------------------

  ;;---
  ;; SmartParens & Web-Mode
  ;;---
  (imp:eval:after smartparens
    (defun mantle:user:web:is-auto-close-style-3 (_id action _context)
      (and (eq action 'insert)
           (eq web-mode-auto-close-style 3)))
    (sp-local-pair 'web-mode
                   "<" ">"
                   :unless '(:add mantle:user:web:is-auto-close-style-3))

    ;; let smartparens handle these
    (innit:customize-set-variable web-mode-enable-auto-quoting nil)
    (innit:customize-set-variable web-mode-enable-auto-pairing t)

    ;; 1. Remove web-mode auto pairs whose end pair starts with a latter
    ;;    (truncated autopairs like <?p and hp ?>). Smartparens handles these
    ;;    better.
    ;; 2. Strips out extra closing pairs to prevent redundant characters
    ;;    inserted by smartparens.
    (dolist (alist web-mode-engines-auto-pairs)
      (setcdr alist
              (cl-loop for pair in (cdr alist)
                       unless (string-match-p "^[a-z-]" (cdr pair))
                       collect (cons (car pair)
                                     (string-trim-right (cdr pair)
                                                        "\\(?:>\\|]\\|}\\)+\\'")))))
    (setq web-mode-engines-auto-pairs (delq nil web-mode-engines-auto-pairs)))

  ;;---
  ;; Web-Mode Config
  ;;---
  (add-to-list 'web-mode-engines-alist '("elixir" . "\\.eex\\'"))
  (add-to-list 'web-mode-engines-alist '("phoenix" . "\\.[lh]eex\\'"))

  ;; Use // instead of /* as the default comment delimited in JS
  (setf (alist-get "javascript" web-mode-comment-formats nil nil #'equal)
        "//"))


;;------------------------------------------------------------------------------
;; Node / NPM
;;------------------------------------------------------------------------------

(imp:use-package npm-mode
  ;;------------------------------
  :hook
  ;;------------------------------
  ((js-mode typescript-mode) . npm-mode)

  ;;------------------------------
  :general
  ;;------------------------------
  (:prefix  (keybind:prefix :local)
   :states  keybind:leader/local:states
   :keymaps (list 'npm-mode-keymap keybind:leader/local:keymaps)
   ;; TODO: ...Does this work? Binding a whole keymap to a key?
   "n" npm-mode-command-keymap))


;; TODO: A Node.js REPL? https://github.com/abicky/nodejs-repl.el


;;------------------------------------------------------------------------------
;; TypeScript
;;------------------------------------------------------------------------------

(imp:use-package typescript-mode
  ;;------------------------------
  :init
  ;;------------------------------

  ;; NOTE: From Doom; add if need (better?) TSX file support.
  ;; ;; REVIEW We associate TSX files with `typescript-tsx-mode' derived from
  ;; ;;        `web-mode' because `typescript-mode' does not officially support
  ;; ;;        JSX/TSX. See emacs-typescript/typescript.el#4
  ;; (when (featurep! :lang web)
  ;;   (autoload 'typescript-tsx-mode "typescript-mode" nil t))
  ;;
  ;; ;; REVIEW We associate TSX files with `typescript-tsx-mode' derived from
  ;; ;;        `web-mode' because `typescript-mode' does not officially support
  ;; ;;        JSX/TSX. See emacs-typescript/typescript.el#4
  ;; (add-to-list 'auto-mode-alist
  ;;              (cons "\\.tsx\\'"
  ;;                    (if (featurep! :lang web)
  ;;                        #'typescript-tsx-mode
  ;;                      #'typescript-mode)))

  ;; TODO-lsp: This from Doom?
  ;; (imp:eval:after flycheck
  ;;   (flycheck-add-mode 'web-eslint 'web-mode)
  ;;   (flycheck-add-mode 'web-eslint 'typescript-mode)
  ;;   (flycheck-add-mode 'web-eslint 'typescript-tsx-mode)
  ;;   (flycheck-add-mode 'typescript-tslint 'typescript-tsx-mode)
  ;;
  ;;   (add-hook! 'typescript-tsx-mode-hook
  ;;     (defun +web-disable-tide-checkers-h ()
  ;;       (pushnew! flycheck-disabled-checkers
  ;;                 'web-jshint
  ;;                 'tsx-tide
  ;;                 'jsx-tide))))

  (innit:hook:defun
      (:name   'typescript:settings
       :file   macro<imp>:path/file
       :docstr "Settings for Typescript mode. Non-LSP stuff.")

     ;; 'wide' is a decent default, probably?
     (setq fill-column (jerky:get 'fill-column 'wide))

     (setq tab-width (jerky:get 'code 'tab 'standard))

    ;; Separate camel-case into separate words?
    ;; (subword-mode t)

     ;; NOTE: Delete this if the line brakes act fucky.
     (setq comment-line-break-function #'js2-line-break)

     ;; Most projects use either eslint, prettier, .editorconfig, or tsf in order
     ;; to specify indent level and formatting. In the event that no
     ;; project-level config is specified (very rarely these days), the community
     ;; default is 2, not 4. However, respect what is in tsfmt.json if it is
     ;; present in the project
     (setq typescript-indent-level (or (and (bound-and-true-p tide-mode)
                                      (plist-get (tide-tsfmt-options) :indentSize))
                                 typescript-indent-level))

     ;; Doom Fix #5556: expand .x to className="x" instead of class="x", if
    ;; `emmet-mode' is used.
    (setq emmet-expand-jsx-className? t))


  ;;------------------------------
  :hook
  ;;------------------------------
  ((typescript-mode-hook . mantle:hook:typescript:settings)
   ;; (typescript-mode-hook . rainbow-delimiters-mode)
   ;;  (typescript-tsx-mode-hook . rainbow-delimiters-mode))
   )


  ;;------------------------------
  :config
  ;;------------------------------

  ;; NOTE: From Doom; add if need TSX file support.
  ;; (when (fboundp 'web-mode)
  ;;   (define-derived-mode typescript-tsx-mode web-mode "TypeScript-TSX")
  ;;   (when (featurep! +lsp)
  ;;     (after! lsp-mode
  ;;       (add-to-list 'lsp--formatting-indent-alist '(typescript-tsx-mode . typescript-indent-level)))))

    ;; HACK Fixes comment continuation on newline
  (autoload 'js2-line-break "js2-mode" nil t))







(imp:use-package web-mode
  ;; TODO: Add cask?
  ;; https://github.com/cask/cask
  ;; :mode ("\\.Cask\\'" . web-mode)

  ;;------------------------------
  :init
  ;;------------------------------

  (defun mantle:user:web:edebug:instrument-defun/on ()
    "Enable instrumentalization for the function under `defun'."
    (interactive)
    (eval-defun 'edebugit))

  (defun mantle:user:web:edebug:instrument-defun/off ()
    "Disable instrumentalization for the function under `defun'."
    (interactive)
    (eval-defun nil))


  (defun mantle:user:web:indent-function (indent-point state)
    "Indent plists more sensibly than `lisp-indent-function'.

Adapted from Doom's `+web-indent-function'in
\"modules/lang/web/autoload.el\", which was adapted from
https://emacs.stackexchange.com/questions/10230/how-to-indent-keywords-aligned"
    (let ((normal-indent (current-column))
          (orig-point (point))
          target)
      (goto-char (1+ (elt state 1)))
      (parse-partial-sexp (point) calculate-lisp-indent-last-sexp 0 t)
      (cond ((and (elt state 2)
                  (or (not (looking-at-p "\\sw\\|\\s_"))
                      (eq (char-after) ?:)))
             (unless (> (save-excursion (forward-line 1) (point))
                        calculate-lisp-indent-last-sexp)
               (goto-char calculate-lisp-indent-last-sexp)
               (beginning-of-line)
               (parse-partial-sexp (point) calculate-lisp-indent-last-sexp 0 t))
             (backward-prefix-chars)
             (current-column))
            ((and (save-excursion
                    (goto-char indent-point)
                    (skip-syntax-forward " ")
                    (not (eq (char-after) ?:)))
                  (save-excursion
                    (goto-char orig-point)
                    (and (eq (char-after) ?:)
                         (eq (char-before) ?\()
                         (setq target (current-column)))))
             (save-excursion
               (move-to-column target t)
               target))
            ((let* ((function (buffer-substring (point) (progn (forward-sexp 1) (point))))
                    (method (or (function-get (intern-soft function) 'lisp-indent-function)
                                (get (intern-soft function) 'lisp-indent-hook))))
               (cond ((or (eq method 'defun)
                          (and (null method)
                               (> (length function) 3)
                               (string-match-p "\\`def" function)))
                      (lisp-indent-defform state indent-point))
                     ((integerp method)
                      (lisp-indent-specform method state indent-point normal-indent))
                     (method
                      (funcall method indent-point state))))))))

  (innit:hook:defun
      (:name   'web:settings
       :file   macro<imp>:path/file
       :docstr "Settings for Emacs Lisp mode. Non-LSP stuff.")
    ;; Emacs' built-in elisp files use a hybrid tab->space indentation scheme
    ;; with a tab width of 8. Any smaller and the indentation will be
    ;; unreadable. Since Emacs' lisp indenter doesn't respect this variable it's
    ;; safe to ignore this setting otherwise.
    (setq tab-width 8)

    ;; Shorter name in modeline
    (setq mode-name "Elisp")

    ;; ;; Don't treat autoloads or sexp openers as outline headers, we have
    ;; ;; hideshow for that.
    ;; (setq outline-regexp +web-outline-regexp)

    ;; Fixed indenter that intends plists sensibly.
    (setq lisp-indent-function #'mantle:user:web:indent-function))


  ;;------------------------------
  :hook
  ;;------------------------------
  ((web-mode-hook . mantle:hook:web:settings)
   ;; TODO: Is Flycheck usable without this?
   ;; ;; Flycheck's two web checkers produce a *lot* of false positives in
   ;; ;; emacs configs, so we disable `web-checkdoc' and reduce the
   ;; ;; `web' checker's verbosity.
   ;; (flycheck-mode-hook #'+web-reduce-flycheck-errors-in-emacs-config-h)
   )


  ;;------------------------------
  :general
  ;;------------------------------
  ;;---
  ;; Debug...
  ;;---
  (:prefix  (keybind:prefix :local "d")
   :states  keybind:leader/local:states
   :keymaps '(web-mode-map lisp-interaction-mode-map keybind:leader/local:keymaps)
   "f" (list #'mantle:user:web:edebug:instrument-defun/on :which-key "`edebug' instrument enable")
   "F" (list #'mantle:user:web:edebug:instrument-defun/off :which-key "`edebug' instrument disable"))

  ;;---
  ;; Eval...
  ;;---
  (:prefix  (keybind:prefix :local "e")
   :states  keybind:leader/local:states
   :keymaps '(web-mode-map lisp-interaction-mode-map keybind:leader/local:keymaps)
   ;; TODO: Try these without "Display Names" and see if it actually is better?
   ;; Doom doesn't bother with a pretty name.
   "b" #'eval-buffer       ; (list #'eval-buffer       :which-key "Eval Buffer")
   "d" #'eval-defun        ; (list #'eval-defun        :which-key "Eval Defun")
   "e" #'eval-last-sexp    ; (list #'eval-last-sexp    :which-key "Eval Last Sexp")
   "E" #'pp-eval-last-sexp ; (list #'pp-eval-last-sexp :which-key "Eval Last Sexp: Pretty Print")
   "r" #'eval-region       ; (list #'eval-region       :which-key "Eval Region")
   "l" #'load-library      ; (list #'load-library      :which-key "Load Library")
   )

  ;;---
  ;; "Go To Considered Harmful"
  ;;---
  (:prefix  (keybind:prefix :local "g")
   :states  keybind:leader/local:states
   :keymaps '(web-mode-map lisp-interaction-mode-map keybind:leader/local:keymaps)
   ;; TODO: Try these without "Display Names" and see if it actually is better?
   ;; Doom doesn't bother with a pretty name.
   "f" #'find-function
   "F" #'find-function-at-point
   "v" #'find-variable
   "l" #'find-library)

  ;;------------------------------
  :config
  ;;------------------------------

  ;; ;; variable-width indentation is superior in elisp. Otherwise, `dtrt-indent'
  ;; ;; and `editorconfig' would force fixed indentation on elisp.
  ;; (add-to-list 'doom-detect-indentation-excluded-modes 'web-mode)

  ;; ;; Enhance elisp syntax highlighting, by highlighting Doom-specific
  ;; ;; constructs, defined symbols, and truncating :pin's in `package!' calls.
  ;; (font-lock-add-keywords
  ;;  'web-mode
  ;;  (append `(;; custom Doom cookies
  ;;            ("^;;;###\\(autodef\\|if\\|package\\)[ \n]" (1 font-lock-warning-face t)))
  ;;          ;; Shorten the :pin of `package!' statements to 10 characters
  ;;          `(("(package!\\_>" (0 (+web-truncate-pin))))
  ;;          ;; highlight defined, special variables & functions
  ;;          (when +web-enable-extra-fontification
  ;;            `((+web-highlight-vars-and-faces . +web--face)))))

  (define-advice elisp-get-var-docstring (:around (fn sym) mantle:advice:append-value)
    "Display variable value next to documentation in eldoc."
    (when-let (ret (funcall fn sym))
      (if (boundp sym)
          (concat ret " "
                  (let* ((truncated " [...]")
                         (print-escape-newlines t)
                         (str (symbol-value sym))
                         (str (prin1-to-string str))
                         (limit (- (frame-width) (length ret) (length truncated) 1)))
                    (format (format "%%0.%ds%%s" (max limit 0))
                            (propertize str 'face 'warning)
                            (if (< (length str) limit) "" truncated))))
        ret))))


;; Make quoted symbols easier to distinguish from free variables
;; https://github.com/Fanael/highlight-quoted
(imp:use-package highlight-quoted
  ;;------------------------------
  :hook
  ;;------------------------------
  (web-mode-hook . highlight-quoted-mode))


;; TODO: in `elisp-def' use-package:
;; ;; Recenter window after following definition
;;   (advice-add #'elisp-def :after #'doom-recenter-a)


;;------------------------------
;; REPL
;;------------------------------

(imp:use-package ielm
  :defer t

  ;;------------------------------
  :config
  ;;------------------------------

  ;; Adapted from http://www.modernemacs.com/post/comint-highlighting/ to add
  ;; syntax highlighting to ielm REPLs.
  (setq ielm-font-lock-keywords
        (append '(("\\(^\\*\\*\\*[^*]+\\*\\*\\*\\)\\(.*$\\)"
                   (1 font-lock-comment-face)
                   (2 font-lock-constant-face)))
                (when (require 'highlight-numbers nil t)
                  (highlight-numbers--get-regexp-for-mode 'web-mode))
                (cl-loop for (matcher . match-highlights)
                         in (append lisp-el-font-lock-keywords-2
                                    lisp-cl-font-lock-keywords-2)
                         collect
                         `((lambda (limit)
                             (when ,(if (symbolp matcher)
                                        `(,matcher limit)
                                      `(re-search-forward ,matcher limit t))
                               ;; Only highlight matches after the prompt
                               (> (match-beginning 0) (car comint-last-prompt))
                               ;; Make sure we're not in a comment or string
                               (let ((state (syntax-ppss)))
                                 (not (or (nth 3 state)
                                          (nth 4 state))))))
                           ,@match-highlights)))))


;;------------------------------------------------------------------------------
;; Tests
;;------------------------------------------------------------------------------

;; https://github.com/tonini/overseer.el
(imp:use-package overseer
  ;;------------------------------
  :config
  ;;------------------------------

  (define-advice overseer--current-buffer-test-file-p (:override (fn sym) mantle:advice:content-not-filename)
    "Test files are test files because of their contents, not their filename?

`overseer' only checks if the filenam ends in \"-test.el\" exactly. That's too
restrictive. Instead, check if the word \"test\" is in the start of the file."
    ;; Will return nil or a buffer position, so already ok for a return value.
    (buffer:search:header "test" :case 'ignore)))


;; https://github.com/jorgenschaefer/emacs-buttercup
(imp:use-package buttercup
  :defer t

  ;;------------------------------
  :minor ; from `auto-minor-mode'
  ;;------------------------------
  ;; TODO: Am I allowed to use `rx-to-string' directly?
  ;; (rx-to-string
  ;;  '(sequence
  ;;    "/"
  ;;    "test"
  ;;    (or "/" "-")
  ;;    (one-or-more any)
  ;;    ".el"
  ;;    string-end)
  ;;  :no-group)
  ("/test[/-].+\\.el\\'" . buttercup-minor-mode)


  ;;------------------------------
  :preface
  ;;------------------------------
  ;; `buttercup' doesn't define a keymap for `buttercup-minor-mode', so we have
  ;; to fool its internal `define-minor-mode' call into thinking one exists, so
  ;; that it will associate it with the mode.
  (defvar buttercup-minor-mode-map (make-sparse-keymap))


  ;;------------------------------
  :init
  ;;------------------------------

  (defun mantle:user:web:buttercup:run-file ()
    "Run all buttercup tests in the focused buffer.

Originally from Doom's `+web/buttercup-run-file' in
\"modules/lang/web/autoload.el\"."
    (interactive)
    (let ((load-path
           (append (list (path:current:dir)
                         (or (path:project:root)
                             default-directory))
                   load-path))
          (buttercup-suites nil))
      (save-selected-window
        (eval-buffer)
        (buttercup-run))
      (message "File executed successfully")))

  (defun mantle:user:web:buttercup:run-project ()
    "Run all buttercup tests in the project.

Originally from Doom's `+web/buttercup-run-project' in
\"modules/lang/web/autoload.el\"."
    (interactive)
    (let* ((default-directory (path:project:root))
           (load-path (append (list (path:join default-directory "test")
                                    default-directory)
                              load-path))
           (buttercup-suites nil))
      (buttercup-run-discover)))


  ;;------------------------------
  :general
  ;;------------------------------
  (:prefix  (keybind:prefix :local "t") ; test
   :states  keybind:leader/local:states
   :keymaps '(buttercup-minor-mode-map keybind:leader/local:keymaps)
   "t" (list #'mantle:user:web:buttercup:run-file :which-key "buttercup: run file")
   "a" (list #'mantle:user:web:buttercup:run-project :which-key "buttercup: run project")
   "s" (list #'buttercup-run-at-point :which-key "buttercup: run at point"))


  ;;------------------------------
  :config
  ;;------------------------------

  ;; (set-popup-rule! "^\\*Buttercup\\*$" :size 0.45 :select nil :ttl 0)

  ;; Add any `buttercup' minor-mode snippets to `yasnippet'.
  (mantle:user:yasnippet:minor-mode/add buttercup-minor-mode)

  (imp:eval:after evil
    (add-hook 'buttercup-minor-mode-hook #'evil-normalize-keymaps)))


;;------------------------------------------------------------------------------
;; Macros
;;------------------------------------------------------------------------------

;; Provides a very helpful elisp macro debugging tool: `macrostep-expand'
(imp:use-package macrostep

  ;;--------------------
  :general
  ;;--------------------
  (:prefix  (keybind:prefix :local "")
   :states  keybind:leader/local:states
   :keymaps '(web-mode-map keybind:leader/local:keymaps)
   "m" '(macrostep-expand :which-key "Expand Macro")))


;; TODO: General Flycheck set-up in "common.el"? Steal from Doom?
;; ;;------------------------------------------------------------------------------
;; ;; Flycheck (TODO: & Cask?)
;; ;;------------------------------------------------------------------------------
;;
;; https://github.com/flycheck/flycheck-cask
;; (imp:use-package flycheck-cask
;;   :defer t
;;
;;   ;;------------------------------
;;   :init
;;   ;;------------------------------
;;
;;   (innit:hook:defun
;;       (:name   'web:flycheck-cask:setup
;;        :file   macro<imp>:path/file
;;        :docstr (mapconcat #'identity
;;                           '("Hook `flycheck-cask-setup' into `flycheck-mode-hook'."
;;                             ""
;;                             "Better deffered/lazy loading, probably?")
;;                           "\n"))
;;     (add-hook 'flycheck-mode-hook #'flycheck-cask-setup
;;               nil
;;               'local))
;;
;;
;;   ;;------------------------------
;;   :hook
;;   ;;------------------------------
;;   (web-mode-hook . mantle:hook:web:flycheck-cask:setup))
;;
;;
;; (imp:use-package flycheck-package
;;   :after flycheck
;;
;;   ;;------------------------------
;;   :config
;;   ;;------------------------------
;;   (flycheck-package-setup))


;;------------------------------------------------------------------------------
;; Help
;;------------------------------------------------------------------------------
;; https://github.com/xuchunyang/elisp-demos

(imp:use-package elisp-demos
  :defer t

  ;;------------------------------
  :init
  ;;------------------------------
  (advice-add #'describe-function-1 :after #'elisp-demos-advice-describe-function-1)
  (advice-add #'helpful-update      :after #'elisp-demos-advice-helpful-update)

  (defun mantle:user:elisp-demos:search/file (symbol filepath)
    "Search for SYMBOL's demo/example for `elisp-demos' in FILEPATH."
    (with-temp-buffer
      (insert-file-contents filepath)
      (goto-char (point-min))
      (when (re-search-forward
             (format "^\\* %s$" (regexp-quote (symbol-name symbol)))
             nil t)
        (let (beg end)
          (forward-line 1)
          (setq beg (point))
          (if (re-search-forward "^\\*" nil t)
              (setq end (line-beginning-position))
            (setq end (point-max)))
          (string-trim (buffer-substring-no-properties beg end))))))

  (defun mantle:user:elisp-demos:search/all (symbol)
    "Search all non-`elisp-demos' demo files for SYMBOL's demo/example."
    (let ((filename "elisp-demos.org")
          ;; TODO: Make demos for all of my shit, and add them in here?
          ;; See Doom's 'demos.org' file: "modules/lang/web/demos.org"
          (paths (list (imp:path:root :mis)
                       (imp:path:root :datetime)))
          demo)
      ;;------------------------------
      ;; Search each path.
      ;;------------------------------
      (while (and (null demo)
                  (not (null paths)))
        ;; If the demo file exists, search it for SYMBOL.
        (let ((path (imp:path:join (pop paths) filename)))
          (when (path:exists? path :file)
            (setq demo (mantle:user:elisp-demos:search/file symbol path)))))

      ;;------------------------------
      ;; Return demo string found or nil for "not found".
      ;;------------------------------
      demo))


  ;;------------------------------
  :config
  ;;------------------------------

  (define-advice elisp-demos--search (:around (fn symbol) mantle:user:elisp-demos:add)
    "Add our own demos to help buffers.

NOTE: This function is called when the help buffer is being built - no caching
or anything is done."
    ;;------------------------------
    ;; Search for SYMBOL's example in:
    ;;------------------------------
    ;; 1. `elisp-demos' file.
    (or (funcall fn symbol)
        ;; 2. Our file(s).
        (mantle:user:elisp-demos:search/all symbol))))


;;------------------------------------------------------------------------------
;; Other Packages?
;;------------------------------------------------------------------------------

;; Skewer: Live web development with Emacs
;;   - https://github.com/skeeto/skewer-mode
;; "Provides live interaction with Web, CSS, and HTML in a web browser.
;; Expressions are sent on-the-fly from an editing buffer to be evaluated in
;; the browser, just like Emacs does with an inferior Lisp process in Lisp
;; modes."


;;------------------------------------------------------------------------------
;; The End.
;;------------------------------------------------------------------------------
(imp:provide :mantle 'config 'user 'dev-env 'languages 'web)
