#+TITLE:       Notes.2022-03-21_0_Emacs-27-Dedoomify
#+AUTHOR:      Cole Brown
#+EMAIL:       code@brown.dev
#+DATE:        [2022-05-12]

Color codes for Zenburn.

Copy/pasted here from:
  - =~/path/to/zenburn-theme-dir/zenburn-theme.el=
    - [[file:~/.config/emacs-sn004/packages/elpa/zenburn-theme-20220412.2023/zenburn-theme.el::(defvar zenburn-default-colors-alist]]
  - =./init.el=
    - (aka =<git-root>/mantle/theme/zenburn/init.el=)
    - [[file:init.el::zenburn-override-colors-alist '((zenburn-magenta-bg . "#4D464B"]]


* Color-Code Coloring "Mode"

TODO-color-font-lock: Update to:
  - [ ] Not use same /exact/ function name as code added to =.emacs=.
  - [ ] Reference code added to =.emacs=.

Code originally from: http://xahlee.info/emacs/emacs/emacs_CSS_colors.html


1. Evaluate the block below (put cursor inside sourc block and =C-c C-c=).
2. =M-x font:font-lock:color:hex= to enable.
3. Look at color codes in this buffer, background will be colored to match code.


#+begin_src emacs-lisp
(defun font:font-lock:color:hex ()
  "Syntax color text of the form 「#ff1100」 and 「#abc」 in current buffer.

Originally from:
  `http://xahlee.info/emacs/emacs/emacs_CSS_colors.html' version:2017-03-12"
  (interactive)
  (font-lock-add-keywords
   nil
   '(("#[[:xdigit:]]\\{3\\}"
      (0 (put-text-property
          (match-beginning 0)
          (match-end 0)
          'face (list :background
                      (let* (
                             (ms (match-string-no-properties 0))
                             (r (substring ms 1 2))
                             (g (substring ms 2 3))
                             (b (substring ms 3 4)))
                        (concat "#" r r g g b b))))))
     ("#[[:xdigit:]]\\{6\\}"
      (0 (put-text-property
          (match-beginning 0)
          (match-end 0)
          'face (list :background (match-string-no-properties 0)))))))
  (font-lock-flush))

(font:font-lock:color:hex)
#+end_src


  (defvar zenburn-default-colors-alist
    '(("zenburn-fg-1"     . "#656555")
      ("zenburn-fg-05"    . "#989890") ; close: 'base7 lighten by 0.3
      ("zenburn-fg"       . "#DCDCCC")
      ("zenburn-fg+1"     . "#FFFFEF")
      ("zenburn-fg+2"     . "#FFFFFD")
      ("zenburn-bg-2"     . "#000000")
      ("zenburn-bg-1"     . "#2B2B2B")
      ("zenburn-bg-08"    . "#303030")
      ("zenburn-bg-05"    . "#383838") ; doom: 'bg-alt
      ("zenburn-bg"       . "#3F3F3F")
      ("zenburn-bg+05"    . "#494949")
      ("zenburn-bg+1"     . "#4F4F4F")
      ("zenburn-bg+2"     . "#5F5F5F")
      ("zenburn-bg+3"     . "#6F6F6F") ; doom: 'base7
      ("zenburn-red-6"    . "#6C3333")
      ("zenburn-red-5"    . "#7C4343") ; close: 'red-4 darken by 0.1
      ("zenburn-red-4"    . "#8C5353") ; doom: 'red-4
      ("zenburn-red-3"    . "#9C6363")
      ("zenburn-red-2"    . "#AC7373")
      ("zenburn-red-1"    . "#BC8383") ; doom: 'red-1
      ("zenburn-red"      . "#CC9393")
      ("zenburn-red+1"    . "#DCA3A3")
      ("zenburn-red+2"    . "#ECB3B3")
      ("zenburn-orange"   . "#DFAF8F") ; doom: 'orange
      ("zenburn-yellow-2" . "#D0BF8F")
      ("zenburn-yellow-1" . "#E0CF9F")
      ("zenburn-yellow"   . "#F0DFAF")
      ("zenburn-green-5"  . "#2F4F2F")
      ("zenburn-green-4"  . "#3F5F3F")
      ("zenburn-green-3"  . "#4F6F4F") ; close: 'green-2 darken by 0.15
      ("zenburn-green-2"  . "#5F7F5F") ; doom: 'green-2
      ("zenburn-green-1"  . "#6F8F6F")
      ("zenburn-green"    . "#7F9F7F")
      ("zenburn-green+1"  . "#8FB28F")
      ("zenburn-green+2"  . "#9FC59F") ; doom: 'green+2
      ("zenburn-green+3"  . "#AFD8AF")
      ("zenburn-green+4"  . "#BFEBBF")
      ("zenburn-cyan"     . "#93E0E3")
      ("zenburn-blue+3"   . "#BDE0F3")
      ("zenburn-blue+2"   . "#ACE0E3")
      ("zenburn-blue+1"   . "#94BFF3")
      ("zenburn-blue"     . "#8CD0D3")
      ("zenburn-blue-1"   . "#7CB8BB") ; doom: 'blue-1
      ("zenburn-blue-2"   . "#6CA0A3")
      ("zenburn-blue-3"   . "#5C888B") ; doom: 'blue-3
      ("zenburn-blue-4"   . "#4C7073")
      ("zenburn-blue-5"   . "#366060")
      ("zenburn-magenta"  . "#DC8CC3"))) ; doom: 'magenta

  (zenburn-override-colors-alist '((zenburn-magenta-bg   . "#4D464B")
                                   (zenburn-magenta-bg-1 . "#5C4D57")
                                   (zenburn-magenta-bg-2 . "#6A5463")
                                   (zenburn-magenta-bg-3 . "#785B6F")
                                   (zenburn-magenta-bg-4 . "#86627B")
                                   (zenburn-magenta-bg-5 . "#956987")
                                   (zenburn-violet       . "#a9a1e1")
                                   (zenburn-magenta-01   . "#c67eaf")
                                   (zenburn-magenta-03   . "#9a6288")))

(doom-darken (doom-color 'magenta) 0.3)  "#9a6288"

* Default Colors

Comments matching up a few of Doom's Zenburn colors or my customizations to actual Zenburn colors.

#+begin_src emacs-lisp
  (defvar zenburn-default-colors-alist
    '(("zenburn-fg-1"     . "#656555")
      ("zenburn-fg-05"    . "#989890") ; close: 'base7 lighten by 0.3
      ("zenburn-fg"       . "#DCDCCC")
      ("zenburn-fg+1"     . "#FFFFEF")
      ("zenburn-fg+2"     . "#FFFFFD")
      ("zenburn-bg-2"     . "#000000")
      ("zenburn-bg-1"     . "#2B2B2B")
      ("zenburn-bg-08"    . "#303030")
      ("zenburn-bg-05"    . "#383838") ; doom: 'bg-alt
      ("zenburn-bg"       . "#3F3F3F")
      ("zenburn-bg+05"    . "#494949")
      ("zenburn-bg+1"     . "#4F4F4F")
      ("zenburn-bg+2"     . "#5F5F5F")
      ("zenburn-bg+3"     . "#6F6F6F") ; doom: 'base7
      ("zenburn-red-6"    . "#6C3333")
      ("zenburn-red-5"    . "#7C4343") ; close: 'red-4 darken by 0.1
      ("zenburn-red-4"    . "#8C5353") ; doom: 'red-4
      ("zenburn-red-3"    . "#9C6363")
      ("zenburn-red-2"    . "#AC7373")
      ("zenburn-red-1"    . "#BC8383") ; doom: 'red-1
      ("zenburn-red"      . "#CC9393")
      ("zenburn-red+1"    . "#DCA3A3")
      ("zenburn-red+2"    . "#ECB3B3")
      ("zenburn-orange"   . "#DFAF8F") ; doom: 'orange
      ("zenburn-yellow-2" . "#D0BF8F")
      ("zenburn-yellow-1" . "#E0CF9F")
      ("zenburn-yellow"   . "#F0DFAF")
      ("zenburn-green-5"  . "#2F4F2F")
      ("zenburn-green-4"  . "#3F5F3F")
      ("zenburn-green-3"  . "#4F6F4F") ; close: 'green-2 darken by 0.15
      ("zenburn-green-2"  . "#5F7F5F") ; doom: 'green-2
      ("zenburn-green-1"  . "#6F8F6F")
      ("zenburn-green"    . "#7F9F7F")
      ("zenburn-green+1"  . "#8FB28F")
      ("zenburn-green+2"  . "#9FC59F") ; doom: 'green+2
      ("zenburn-green+3"  . "#AFD8AF")
      ("zenburn-green+4"  . "#BFEBBF")
      ("zenburn-cyan"     . "#93E0E3")
      ("zenburn-blue+3"   . "#BDE0F3")
      ("zenburn-blue+2"   . "#ACE0E3")
      ("zenburn-blue+1"   . "#94BFF3")
      ("zenburn-blue"     . "#8CD0D3")
      ("zenburn-blue-1"   . "#7CB8BB") ; doom: 'blue-1
      ("zenburn-blue-2"   . "#6CA0A3")
      ("zenburn-blue-3"   . "#5C888B") ; doom: 'blue-3
      ("zenburn-blue-4"   . "#4C7073")
      ("zenburn-blue-5"   . "#366060")
      ("zenburn-magenta"  . "#DC8CC3"))) ; doom: 'magenta
#+end_src


* Custom Colors

#+begin_src emacs-lisp
  (zenburn-override-colors-alist '((zenburn-magenta-bg   . "#4D464B")
                                   (zenburn-magenta-bg-1 . "#5C4D57")
                                   (zenburn-magenta-bg-2 . "#6A5463")
                                   (zenburn-magenta-bg-3 . "#785B6F")
                                   (zenburn-magenta-bg-4 . "#86627B")
                                   (zenburn-magenta-bg-5 . "#956987")
                                   (zenburn-violet       . "#a9a1e1")
                                   (zenburn-magenta-01   . "#c67eaf")
                                   (zenburn-magenta-03   . "#9a6288")))
#+end_src
